#!/usr/bin/env bash

PKGS_FORK=$HOME/git/nixpkgs
PKGS_UNSTABLE=$HOME/.nix-defexpr/channels/nixos-unstable
PKGS_STABLE=$HOME/.nix-defexpr/channels/nixos-16.03

case "$HOSTNAME" in
  annemarie ) PKGS=$PKGS_STABLE ;;
  renzo     ) PKGS=$PKGS_STABLE ;;
  mandeeza  ) PKGS=$PKGS_STABLE   ;;
esac

echo "Package directory: " $PKGS
echo

sudo env NIXOS_CONFIG=$HOME/nix/sys.nix \
         HOSTNAME=$HOSTNAME \
  nixos-rebuild -I $PKGS switch "$@"
