#!/usr/bin/env bash

# Print the name of the current branch
cd "$NIXPKGS_ALL"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo ""
echo "nixpkgs branch: $BRANCH"
echo ""

sudo \
  env NIXOS_CONFIG=$NIXOS_CONFIG \
  nixos-rebuild -I nixpkgs="$NIXPKGS_ALL" switch
