# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/chris/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-13.17
extra-deps:
  - texrunner-0.0.1.2@sha256:e4ba747a3c059c727953b9596e45e867d5305b55132b6040b03ebd9cbb5feb8c
