steps:

  - imports:
      align: group
      list_align: after_alias
      long_list_align: new_line
      list_padding: 4
      separate_lists: true

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - trailing_whitespace: {}

columns: 80
