resolver: lts-11.7

packages:
  - .

flags:
  xmonad-extras:
    with_hint: false
    with_mpd: false
  xmonad-contrib:
    use_xft: false

#extra-deps:
#  - alsa-core-0.5.0.1
#  - alsa-mixer-0.2.0.3
#  - X11-1.8
#  - xmonad-0.13
#  - xmonad-contrib-0.13
#  - xmonad-extras-0.13.0

nix:
  packages:
    - alsaLib
    - pkgconfig
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXext
    - xorg.libXpm
