#!/usr/bin/env bash

# Print the name of the current branch
cd "$NIXPKGS_ALL"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo ""
echo "nixpkgs branch: $BRANCH"
echo ""

env NIXPKGS_CONFIG=$HOME/.nix/user-stable.nix \
    nix-env \
    -i all-stable \
    -f $STABLE $HOME/.nix-defexpr/channels/nixos-15.09

env NIXPKGS_CONFIG=$HOME/.nix/user-unstable.nix \
    nix-env \
    -i all-unstable \
    -f $HOME/.nix-defexpr/channels/nixos-unstable
