#!/usr/bin/env bash

# Print the name of the current branch
cd "$NIXPKGS_ALL"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo ""
echo "nixpkgs branch: $BRANCH"
echo ""

export NIXPKGS_CONFIG

nix-env -i all -f "$NIXPKGS_ALL"
