#!/usr/bin/env bash

NIX_PKGS="$HOME/git/nixpkgs"

# Print the name of the current branch
cd "$NIX_PKGS"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo ""
echo "nixpkgs branch: $BRANCH"
echo ""

nix-env -i all -f "$NIX_PKGS"
