p: with p; [
    acme-functors
    aeson
    aeson-optics
    appendmap
    async
    atomic-modify
    attoparsec
    aws-cloudfront-signed-cookies
    base16-bytestring
    blaze-html
    blaze-markup
    cookie
    conduit-combinators
    cryptonite
    data-forest
    Decimal
    diagrams
    either-list-functions
    filemanip
    foldl
    fsnotify
    gd
    gtk3
    hashable
    hasql
    hasql-dynamic-statements
    hasql-notifications
    hasql-transaction
    hedgehog
    hex-text
    hnix
    html-entities
    http-client
    http-client-tls
    http-conduit
    http-types
    ini
    lens
    lens-aeson
    loc
    loc-test
    lucid
    markdown
    megaparsec
    memory
    monad-gen
    multi-instance
    mvar-lock
    neat-interpolation
    network
    network-simple
    network-uri
    one-line-aeson-text
    one-liner
    opaleye
    optics
    optparse-applicative
    optparse-generic
    pam
    pandoc
    pandoc-types
    parser-combinators
    partial-semigroup
    partial-semigroup-hedgehog
    path
    path-io
    path-text-utf8
    pipes
    pipes-attoparsec
    pipes-bytestring
    pipes-http
    pipes-safe
    pipes-text
    postgresql-simple
    profunctors
    QuickCheck
    random
    relude
    rel8
    resource-pool
    resourcet
    rss
    safe-exceptions
    safe-money
    scotty
    semialign
    stm-containers
    stripe-concepts
    stripe-scotty
    stripe-signature
    stripe-wreq
    these
    template
    test-framework
    text-replace
    turtle
    unordered-containers
    utf8-string
    validation
    var-monad
    vector
    wai
    warp
    wreq
    X11
]
